---
title: "BYU-Idaho Math326: Design and Analysis of Experiments"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## An Customizable Textbook

This book is meant to be a starting point for you to learn design and analysis of experiments. You should feel free to edit the Rmarkdown files so that the book becomes your own.

### How to Use This Book

Under Principles of Experiments the most foundational issues that face each experimenter are described.

The Specific Designs section addresses specific designs we will learn about in this course. Each design will have an image next to it representing the diagram of the structural factors. 

This list is by no means exhaustive. The taxonomy used for the drop-down works well when we want to cover just these basic few designs but a new taxonomy may work better if more complex designs are considered. Within each of these designs there are subsections: 

* Overview
* Design
* Decomposition
* R instructions: code illustrating how to run the model
* Resources
    
The section labeled Broad Topics seeks to address topics that are relevant to many experiment designs.

Finally, a section dedicated to R code that can be used in multiple designs. This includes numerical and graphical data summaries as well as code for model diagnostics/assumption checking.

You are welcome to add additional specific designs or add to the list of broad topics.

#### Suggested Sequence of Topics for Teaching

This book was specifically designed for the Math326 Design and Analysis of Experiments class at BYU-Idaho, as it stands in 2022. BYU-I follows a 14 week semester. After introducing some foundational principles of experimental design, the recommended sequence follows the general pattern of

* Introduce a specific design: suitability/benefits of the design, explanation of the design, factor structure and decomposition, steps for analysis (including R code)
* Discuss new topics/complexities/considerations associated with that design located in the Broad Topics list.

## Book Scope

This is an introductory book intended to familiarize students with foundational concepts and vocabulary in the design and analysis of experiments. The designs covered in this book are the most basic and all assume a continuous response variable. Hopefully with this foundation students will be prepared to excel in experimental design and analysis courses in grad school, or be able to extend these principles to more complex designs as practitioners.


